/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author 1nternetslav3
 */
public class frameDataMasterMember extends javax.swing.JFrame {

    /**
     * Creates new form frameDataMasterKaryawan
     */
    public frameDataMasterMember() {
        initComponents();
        kode();
      //  idkaryawan();
    }
     private void kode(){
    
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID Member");
        model.addColumn("Nama Member");
        model.addColumn("No. Telp");
        model.addColumn("Alamat");
        
        
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from member";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            table.setModel(model);
        } catch (Exception e) {
        } }
     
        private void kosong(){
        txt_idkaryawan.setText(null);
        txt_namakaryawan.setText(null);
        txt_notelp.setText(null);  
        txt_alamat.setText(null);
        
        
        }
        
     private void idkaryawan() {
        try {
            String sql = "SELECT id_member FROM member order by id_member desc";
            Connection conn = (Connection) koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            if (rs.next()) {
                String Idno = rs.getString("id_member").substring(2);
                String AN = "" + (Integer.parseInt(Idno) + 1);
                String Nol = "";
                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

                txt_idkaryawan.setText("MB" + Nol + AN);
            } else {
                txt_idkaryawan.setText("MB0001");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    private void soundClick(){
    try {
    File sound = new File("C:\\Users\\Windows 10\\Downloads\\MUSIC\\click.wav");
    Clip c = AudioSystem.getClip();
    c.open(AudioSystem.getAudioInputStream(sound));
    c.start();
        } catch (Exception e){       
          }
    }
        
        
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_notelp = new javax.swing.JTextField();
        txt_idkaryawan = new javax.swing.JTextField();
        txt_namakaryawan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        btn_datamaster = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_laporan1 = new javax.swing.JButton();
        txt_alamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ui_component/icon.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_notelp.setBackground(new java.awt.Color(217, 217, 217));
        txt_notelp.setBorder(null);
        txt_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpActionPerformed(evt);
            }
        });
        getContentPane().add(txt_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, -1));

        txt_idkaryawan.setBackground(new java.awt.Color(217, 217, 217));
        txt_idkaryawan.setBorder(null);
        txt_idkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idkaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, -1));

        txt_namakaryawan.setBackground(new java.awt.Color(217, 217, 217));
        txt_namakaryawan.setBorder(null);
        txt_namakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namakaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(txt_namakaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, -1));

        table.setDefaultEditor(Object.class, null);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 510, 410));

        btn_tambah.setOpaque(false);
        btn_tambah.setContentAreaFilled(false);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 80, 30));

        btn_hapus.setOpaque(false);
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 80, 30));

        btn_laporan.setOpaque(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 60, 90));

        btn_transaksi.setOpaque(false);
        btn_transaksi.setContentAreaFilled(false);
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 70, 70));

        btn_dashboard.setOpaque(false);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 70, 80));

        btn_datamaster.setOpaque(false);
        btn_datamaster.setContentAreaFilled(false);
        btn_datamaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datamasterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_datamaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 90, 80));

        btn_edit.setOpaque(false);
        btn_edit.setContentAreaFilled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 70, 40));

        btn_clear.setOpaque(false);
        btn_clear.setContentAreaFilled(false);
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 270, 30));

        btn_laporan1.setOpaque(false);
        btn_laporan1.setContentAreaFilled(false);
        btn_laporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 80, 70));

        txt_alamat.setBackground(new java.awt.Color(217, 217, 217));
        txt_alamat.setBorder(null);
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_revisi/master member revisi.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpActionPerformed

    private void txt_idkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idkaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idkaryawanActionPerformed

    private void txt_namakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namakaryawanActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Member");
        model.addColumn("Nama Member");
        model.addColumn("No. Telepon");
        model.addColumn("Alamat");
        
        
        try{ 
        String nama = txt_namakaryawan.getText();
        String sql = "SELECT * FROM member WHERE nama_member LIKE '%"+nama+"%'";
        Connection conn = (Connection) koneksi.getKoneksi();
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        
       while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
            table.setModel(model);
           
        
       }catch(SQLException | ClassNotFoundException e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_txt_namakaryawanActionPerformed

    private void btn_datamasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datamasterActionPerformed
       soundClick();
        dispose();
         new master().setVisible(true);
    }//GEN-LAST:event_btn_datamasterActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        soundClick();
        dispose();
         new framePenjualan().setVisible(true);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        soundClick();
        String notelp1 = txt_notelp.getText();       
        char[] chars = notelp1.toCharArray();
               
        if (txt_idkaryawan.getText().equals("")|| txt_namakaryawan.getText().equals("") || txt_notelp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"lengkapi data");                          
            
        } else if(chars[0]!='0'){
                JOptionPane.showMessageDialog(null, "Format nomor dimulai dengan 08");
                txt_notelp.setText("");
        } else if(chars.length<12){
                JOptionPane.showMessageDialog(null, "Format nomor minimal 12 angka");
                
        }else if(chars.length>13){
                JOptionPane.showMessageDialog(null, "Format nomor maksimal 13 angka");
        }
        
        else {
            String idkaryawan = txt_idkaryawan.getText();
            String namakaryawan = txt_namakaryawan.getText();
            String notelp = txt_notelp.getText();
            String alamat = txt_alamat.getText();
                try {
                    Connection c = koneksi.getKoneksi();
                    String sql = "INSERT INTO member VALUES (?,?,?,?)";
                    
                    PreparedStatement p = c.prepareStatement(sql);
                    p.setString(1, idkaryawan);
                    p.setString(2, namakaryawan);
                    p.setString(3, notelp);
                    p.setString(4, alamat);
                    
                    p.executeUpdate();
                    p.close();
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "terjadi kesalahan");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(frameDataMasterMember.class.getName()).log(Level.SEVERE, null, ex);
                }
               kode();
                
               kosong();
                
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                
                }
        idkaryawan();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            String sql = "UPDATE member SET nama_member='" + txt_namakaryawan.getText() + "',notelp='" + txt_notelp.getText()+ "',alamat='" + txt_alamat.getText()+ "' where id_member='" + txt_idkaryawan.getText() + "'";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: "+e.getMessage());
        }
        kode();
        kosong();
        idkaryawan();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
          
        
            int n = JOptionPane.showConfirmDialog(
            null,
            "apakah anda yakin untuk menghapus?",
            "konfirmasi hapus",
            JOptionPane.YES_NO_OPTION);

        if( n == JOptionPane.YES_OPTION){
                    try {
            String sql ="delete from member where id_member='"+txt_idkaryawan.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "hapus dibatalkan");
        }
        

           
           
        kode();
        kosong();
        idkaryawan();
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int baris = table.rowAtPoint(evt.getPoint());
        String idkaryawan =table.getValueAt(baris, 0).toString();
        txt_idkaryawan.setText(idkaryawan);
        
        String nama = table.getValueAt(baris,1).toString();
        txt_namakaryawan.setText(nama);
        
        String notelp=table.getValueAt(baris, 2).toString();
        txt_notelp.setText(notelp);
        
        String alamat=table.getValueAt(baris, 3).toString();
        txt_alamat.setText(alamat);
    }//GEN-LAST:event_tableMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       kosong();
       idkaryawan();
       kode();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        soundClick();
        dispose();
      new dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        soundClick();
        dispose();
      new laporan().setVisible(true);
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_laporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan1ActionPerformed
       soundClick();
        dispose();
      new frameLogin().setVisible(true);
    }//GEN-LAST:event_btn_laporan1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       txt_idkaryawan.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDataMasterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDataMasterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDataMasterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDataMasterMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDataMasterMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_datamaster;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_laporan1;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idkaryawan;
    private javax.swing.JTextField txt_namakaryawan;
    private javax.swing.JTextField txt_notelp;
    // End of variables declaration//GEN-END:variables
} 
