/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author 1nternetslav3
 */
public class master extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public master() {
        initComponents();
    }

    private void soundClick(){
    try {
    File sound = new File("C:\\Users\\Windows 10\\Downloads\\MUSIC\\click.wav");
    Clip c = AudioSystem.getClip();
    c.open(AudioSystem.getAudioInputStream(sound));
    c.start();
    } catch (Exception e){       
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_jual = new javax.swing.JButton();
        btn_lap1 = new javax.swing.JButton();
        btn_lap2 = new javax.swing.JButton();
        btn_lap3 = new javax.swing.JButton();
        btn_lap4 = new javax.swing.JButton();
        btn_beli = new javax.swing.JButton();
        btn_jual1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_jual.setOpaque(false);
        btn_jual.setContentAreaFilled(false);
        btn_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jualActionPerformed(evt);
            }
        });
        getContentPane().add(btn_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 390, 60));

        btn_lap1.setOpaque(false);
        btn_lap1.setContentAreaFilled(false);
        btn_lap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lap1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 100, 90));

        btn_lap2.setOpaque(false);
        btn_lap2.setContentAreaFilled(false);
        btn_lap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lap2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 90, 90));

        btn_lap3.setOpaque(false);
        btn_lap3.setContentAreaFilled(false);
        btn_lap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lap3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 80, 90));

        btn_lap4.setOpaque(false);
        btn_lap4.setContentAreaFilled(false);
        btn_lap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lap4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 70, 80));

        btn_beli.setOpaque(false);
        btn_beli.setContentAreaFilled(false);
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 390, 60));

        btn_jual1.setOpaque(false);
        btn_jual1.setContentAreaFilled(false);
        btn_jual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jual1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_jual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 390, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_revisi/master revisi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lap4ActionPerformed
        soundClick();      
        setVisible(false);
      new framePembelian().setVisible(true);
    }//GEN-LAST:event_btn_lap4ActionPerformed

    private void btn_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jualActionPerformed
        soundClick(); 
        setVisible(false);
      new frameDataMasterSupplier().setVisible(true);
    }//GEN-LAST:event_btn_jualActionPerformed

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed
        soundClick(); 
        setVisible(false);
      new frameDataMasterBarang().setVisible(true);
    }//GEN-LAST:event_btn_beliActionPerformed

    private void btn_lap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lap1ActionPerformed
        soundClick(); 
        setVisible(false);
      new laporan().setVisible(true);
    }//GEN-LAST:event_btn_lap1ActionPerformed

    private void btn_lap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lap2ActionPerformed
        soundClick(); 
        setVisible(false);
      new dashboard().setVisible(true);
    }//GEN-LAST:event_btn_lap2ActionPerformed

    private void btn_lap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lap3ActionPerformed
        soundClick(); 
        setVisible(false);
      new framePenjualan().setVisible(true);
    }//GEN-LAST:event_btn_lap3ActionPerformed

    private void btn_jual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jual1ActionPerformed
        soundClick(); 
        setVisible(false);
      new frameDataMasterMember().setVisible(true);
    }//GEN-LAST:event_btn_jual1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_beli;
    private javax.swing.JButton btn_jual;
    private javax.swing.JButton btn_jual1;
    private javax.swing.JButton btn_lap1;
    private javax.swing.JButton btn_lap2;
    private javax.swing.JButton btn_lap3;
    private javax.swing.JButton btn_lap4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
